# GENERATE TIME: Mon Apr 17 08:56:20 2023
# CMD:
# /root/BasicSR/basicsr/train.py -opt /root/BasicSR/options/train/train_FuseNet_seed.yml

# general settings
name: PSMFN_x2_C64B8_L1_1000k
model_type: SRModel
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
#    dataroot_gt: /mnt/yxsun/Project/Data/datasets/DIV2K/DIV2K_train_HR_sub
#    dataroot_lq: /mnt/yxsun/Project/Data/datasets/DIV2K/DIV2K_train_LR_bicubic/X4_sub
#    (for lmdb)
    dataroot_gt: /root/autodl-tmp/DF2K/train_HR_sub.lmdb
    dataroot_lq: /root/autodl-tmp/DF2K/train_LR_x2_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb
      # (for lmdb)
      # type: lmdb

    gt_size: 96
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: /root/autodl-tmp/DIV2K_x2/HR
    dataroot_lq: /root/autodl-tmp/DIV2K_x2/LR
    io_backend:
      type: disk

# network structures
network_g:
  type: PSMFN
  num_in_ch: 3
  num_feat: 64
  num_out_ch: 3
  upscale: 2

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: 

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 5e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [1000000]
    restart_weights: [1]
    eta_min: !!float 1e-6

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
    entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
